apiVersion: v1
kind: Service
metadata:
  labels:
    app: TRTSERVER_NAME
  name: TRTSERVER_NAME
  namespace: KUBEFLOW_NAMESPACE
spec:
  ports:
  - name: grpc-trtis-serving
    port: 8001
    targetPort: 8001
  - name: http-trtis-serving
    port: 8000
    targetPort: 8000
  - name: prometheus-metrics
    port: 8002
    targetPort: 8002
  selector:
    app: TRTSERVER_NAME
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-client-ui
  template:
    metadata:
      labels:
        app: demo-client-ui
        role: frontend
    spec:
      containers:
      - name: webapp
        image: <webapp-image>
        imagePullPolicy: Always
        env:
        - name: TRTSERVER_HOST
          value: TRTSERVER_NAME.KUBEFLOW_NAMESPACE
        - name: MODEL_SERVE_NAME
          value: MODEL_PASSIN_NAME
        - name: MODEL_VERSION
          value: "MODEL_PASSIN_VERSION"
        - name: TRTSERVER_PORT
          value: "8001"
        ports:
        - name: http-server
          containerPort: 8080
