apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: TRTSERVER_NAME
  name: TRTSERVER_NAME
  namespace: KUBEFLOW_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TRTSERVER_NAME
  template:
    metadata:
      labels:
        app: TRTSERVER_NAME
        version: v1
    spec:
      containers:
      - image: nvcr.io/nvidia/tensorrtserver:19.03-py3
        command: ["/bin/sh", "-c"]
        args: ["trtserver --model-store=MODEL_PATH"]
        imagePullPolicy: IfNotPresent
        name: TRTSERVER_NAME
        ports:
        - containerPort: 9000
        - containerPort: 8000
        - containerPort: 8001
        - containerPort: 8002
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
            nvidia.com/gpu: 1
          requests:
            cpu: "2"
            memory: 4Gi
            nvidia.com/gpu: 1
        volumeMounts:
        - name: persistent-data-store
          mountPath: /mnt/workspace
      volumes:
      - name: persistent-data-store
        persistentVolumeClaim:
          claimName: nvidia-workspace-read-claim


